version: '3'
services:
  tomcat:
    image: tomcat:latest
    volumes:
      - /Users/gldwn/devops-project:/usr/local/tomcat/webapps
    ports:
      - 8084:8080
  jenkins:
    image: jenkins/jenkins
    volumes:
      - /Users/gldwn/devops-project/jenConfig:/var/jenkins_home
      - /Users/gldwn/devops-project:/home/webapps
    ports:
      - 8083:8080
      - 50000:50000